---
title: "Group 2 Project Report"
format: pdf
editor: visual
author: Danni Cox, Sophia Hemsi, Sarah Mulligan, 
---

## 1.1 Use a discrete density-dependent and -independent population model to assess the population growth dynamics of any three species within the 10 most abundant species. 

```{r}

library('tidyverse')
library('dplyr')
library('DescTools')
library('vegan')

data <- read_csv('/Users/danni/OneDrive/Desktop/Grad School/R Workshop/group2.csv')

# Identify top 3 species

species_abundance <- data |>
  group_by(species) |>
  summarise(total_abundance = sum(n, na.rm = T)) |>
  arrange(desc(total_abundance)) |>
  slice(1:10)

top3species <- species_abundance$species[1:3]

top3species

data$lambda = NA

# top 3 species over time

data_over_time <- data |>
  filter(species %in% top3species) |>
  group_by(species, date) |>
  summarise(N = sum(n, na.rm = T)) |>
  arrange(species, date) |>
  ungroup()

ggplot(data_over_time, aes(x = date, y = N, color = species)) +
  geom_point() +
  geom_line() +
  labs(title = "Abundance of Top 3 Species Over Time",
       x = "Date",
       y = "Abundance",
       color = "Species") +
  theme_bw()
```

```{r}

# density independent model

data_w_lambda <- data_over_time |>
 arrange(species, date) |>
   mutate(lambda = lead(N)/N)

avg_lambda <- data_w_lambda |>
  group_by(species) |>
  summarise(
    mean_lambda = Gmean(lambda, na.rm = T),
    mean_sd = Gsd(lambda, na.rm = T)
  )

avg_lambda

# lambda over time

ggplot(data_w_lambda |> filter(!is.na(lambda)),
       aes(x = date, y = lambda, color = species)) +
  geom_point() +
  geom_line() +
  labs(title = "Lambda Over Time", x = "Date", y = "Lambda", color = "Species") +
  theme_bw()

trends <- avg_lambda |>
  mutate(pop_trends = case_when(
    mean_lambda > 1.0 ~ "Growing",
    mean_lambda == 1.0 ~ "Satble",
    mean_lambda < 1.0 ~ "Declining"
  ))

trends


```

```{r}

# project the population - density independent model

years <- 2000

pop <- data_w_lambda |>
  group_by(species) |>
  slice_max(date, n = 1) |>
  select(species, N_0 = N, t_0 = date) |>
  left_join(avg_lambda, by = "species")

sim <- tibble()

for(i in 1:nrow(pop)) {
  Species <- pop$species[i]
  N0 <- pop$N_0[i]
  lambda <- pop$mean_lambda[i]
  t0 <- pop$t_0[i]
  
  N <- numeric(years + 1)
  N[1] <- N0
  
  for(t in 1:years) {
    N[t + 1] <- lambda * N[t]
  }
  
  projected_pop <- tibble(
    species = Species,
    year = 0:years,
    projection = N,
    t_i = t0 + years(0:years)
  )

sim <- bind_rows(sim, projected_pop)

  
}

sim

ggplot(sim, aes(x = year, y = projection, color = species)) +
  geom_line() +
  labs(title = "Abundance of Top 3 Species Using a\nDensity-Independent Population Model",
       x = "Years", y = "Projected Abundance", color = "Species") +
  theme_bw()
```

```{r}

# density-dependent model

years <- 10000

pop2 <- data_w_lambda |>
  group_by(species) |>
  slice_max(date, n = 1) |>
  select(species, N_0 = N, t_0 = date) |>
  left_join(avg_lambda, by = "species") |>
  mutate(rd = mean_lambda - 1)

K_estimate <- data_over_time |>
  group_by(species) |>
    summarise(K = max(N, na.rm = T))


pop2 <- pop2 |>
  left_join(K_estimate, by = "species")

sim2 <- tibble()

for(i in 1:nrow(pop2)) {
  Species <- pop2$species[i]
  N0 <- pop2$N_0[i]
  rd <- pop2$rd[i]
  K <- pop2$K[i]
  t0 <- pop2$t_0[i]
  
  N <- numeric(years + 1)
  N[1] <- N0
  
  for(t in 1:years) {
    N[t + 1] <- N[t] + rd * N[t] * (1 - N[t] / K)
    
    if (N[t + 1] < 0) {
      N[t + 1] <- 0
  }
}

  projected_pop2 <- tibble(
    species = Species,
    year = 0:years,
    projection = N,
    t_i = t0 + years(0:years),
    K = K,
    rd = rd
  )
  
  sim2 <- bind_rows(sim2, projected_pop2)
}

sim2

ggplot(sim2, aes(x = year, y = projection, color = species)) +
  geom_line() +
  geom_hline(data = sim2 |> distinct(species, K),
             aes(yintercept = K, color = species),
             linetype = "dashed", linewidth = 1) +
  labs(title = "Abundance of Top 3 Species Using\na Density-Dependent Population Model",
    x = "Years",
    y = "Projected Abundance",
    color = "Species"
  ) +
  theme_bw()
```

## What can you infer from both models (Modeli \| Speciesi)? For each species, what is the most proper model to assess their growth? Why?

a;skldjf;a

## 1.2 Based on the selected models, how does lambda change over time?
